In [1]:
import numpy as np

In [2]:
x = np.array([[1,1,0,0,1,0,0,0], [0,0,1,1,1,1,1,1], [0,0,1,2,3,0,0,0]])

In [3]:
x

array([[1, 1, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 2, 3, 0, 0, 0]])

In [15]:
x_tf = x * (1/x.sum(axis = 1)).reshape(-1,1)
x_tf

array([[0.33333333, 0.33333333, 0.        , 0.        , 0.33333333,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.16666667, 0.16666667, 0.16666667,
        0.16666667, 0.16666667, 0.16666667],
       [0.        , 0.        , 0.16666667, 0.33333333, 0.5       ,
        0.        , 0.        , 0.        ]])

In [29]:
x_idf = x_tf * np.log(x.shape[0]/(x>0).sum(axis = 0))
x_idf

array([[0.3662041 , 0.3662041 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.06757752, 0.06757752, 0.        ,
        0.18310205, 0.18310205, 0.18310205],
       [0.        , 0.        , 0.06757752, 0.13515504, 0.        ,
        0.        , 0.        , 0.        ]])